TASK: CASIA2_ResNet18
PRECISION: float64
METRICS_BASE: binary
SEED: 42
DATA_RELOAD: True

DATASET:
  type: HeatmapFaceForensic
  TRAIN: True
  COMPRESSION: c0
  IMAGE_SUFFIX: png
  NUM_WORKERS: 4
  PIN_MEMORY: True
  IMAGE_SIZE: [384, 384]
  HEATMAP_SIZE: [96, 96]
  SIGMA: 2
  ADAPTIVE_SIGMA: True
  HEATMAP_TYPE: gaussian
  SPLIT_IMAGE: False
  DATA:
    TYPE: images
    SAMPLES_PER_VIDEO:
      ACTIVE: True
      TRAIN: 32
      VAL: 32
      TEST: 32
    TRAIN:
      NAME: CASIA2
      ROOT: /mnt/c/Users/vishal.das/Desktop/Project/FakeImageDetection/LAA-Net/LAA-Net/CASIA2/
      FROM_FILE: False
      FAKETYPE: [Tp, Au]
      LABEL_FOLDER: [fake, real]
    VAL:
      NAME: CASIA2
      ROOT: /mnt/c/Users/vishal.das/Desktop/Project/FakeImageDetection/LAA-Net/LAA-Net/CASIA2/
      FROM_FILE: False
      FAKETYPE: [Tp, Au]
      LABEL_FOLDER: [fake, real]
    TEST:
      NAME: CASIA2
      ROOT: /mnt/c/Users/vishal.das/Desktop/Project/FakeImageDetection/LAA-Net/LAA-Net/CASIA2/
      FROM_FILE: False
      FAKETYPE: [Tp, Au]
      LABEL_FOLDER: [fake, real]
  TRANSFORM:
    geometry:
      type: GeometryTransform
      resize: [384, 384, 1]
      normalize: 0
      horizontal_flip: 0.5
      cropping: [0.15, 0.5]
      scale: [0.15, 0.5]
      rand_erasing: [0.5, 1]
    color:
      type: ColorJitterTransform
      clahe: 0.0
      colorjitter: 0.3
      gaussianblur: 0.3
      gaussnoise: 0.3
      jpegcompression: [0.5, 40, 100]
      rgbshift: 0.3
      randomcontrast: 0.0
      randomgamma: 0.5
      randombrightness: 1
      huesat: 1
    normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
  DEBUG: False
  DYNAMIC_FXRAY: False

MODEL:
  type: PoseResNet
  block: BasicBlock
  layers: [2, 2, 2, 2]
  dropout_prob: 0.0
  num_layers: 18
  include_top: False
  include_hm_decoder: True
  head_conv: 64
  use_c2: True
  use_c3: True
  use_c4: True
  use_c51: True
  efpn: True
  tfpn: False
  heads:
    hm: 1
    cls: 1
    cstency: 256
  INIT_WEIGHTS:
    pretrained: True

TRAIN:
  gpus: [0]
  batch_size: 16
  lr: 0.00005
  epochs: 100
  begin_epoch: -1
  warm_up: 6
  every_val_epochs: 1
  loss:
    type: CombinedFocalLoss
    use_target_weight: False
    cls_lmda: 1
    dst_hm_cls_lmda: 0
    offset_lmda: 0
    hm_lmda: 10
    cstency_lmda: 100
    mse_reduction: sum
    ce_reduction: mean
  optimizer: SAM
  distributed: False
  pretrained: ''
  tensorboard: True
  resume: False
  lr_scheduler:
    milestones: [5, 15, 20, 25]
    gamma: 0.5
  freeze_backbone: False
  debug:
    active: False
    save_hm_gt: True
    save_hm_pred: True

TEST:
  gpus: [0]
  subtask: 'eval'
  test_file: ''
  vis_hm: True
  threshold: 0.5
  flip_test: True
  video_level: True
  pretrained: ''

PREPROCESSING:
  DATASET: CASIA2
  SPLIT: train
  ROOT: /mnt/c/Users/vishal.das/Desktop/Project/FakeImageDetection/LAA-Net/LAA-Net/CASIA2/
  FAKETYPE: [Tp, Au]
  IMAGE_SUFFIX: jpg
  DATA_TYPE: images
  LABEL: [fake, real]
  facial_lm_pretrained: pretrained/shape_predictor_68_face_landmarks.dat
  DEBUG: False
