TASK: CASIA2_LAA_Training
PRECISION: float32
METRICS_BASE: binary
SEED: 42
DATA_RELOAD: True

DATASET:
  type: CASIA2Dataset
  TRAIN: True
  IMAGE_SUFFIX: jpg
  NUM_WORKERS: 2
  PIN_MEMORY: True
  IMAGE_SIZE: [384, 384]
  HEATMAP_SIZE: [96, 96]
  SPLIT_IMAGE: False

  DATA:
    TYPE: images
    SAMPLES_PER_VIDEO:
      ACTIVE: False
      TRAIN: 32
      VAL: 32
      TEST: 32
    TRAIN:
      NAME: CASIA2
      ROOT: /kaggle/working/
      FROM_FILE: False
      FAKETYPE: [fake, real]
      LABEL_FOLDER: [real, fake]
    VAL:
      NAME: CASIA2
      ROOT: /kaggle/working/
      FROM_FILE: False
      FAKETYPE: [fake, real]
      LABEL_FOLDER: [real, fake]
    TEST:
      NAME: CASIA2
      ROOT: /kaggle/working/
      FROM_FILE: False
      FAKETYPE: [fake, real]
      LABEL_FOLDER: [real, fake]

  TRANSFORM:
    geometry:
      type: GeometryTransform
      resize: [384, 384, 0]
      normalize: 1
      horizontal_flip: 0.5
    color:
      type: ColorJitterTransform
      colorjitter: 0.2
      gaussianblur: 0.3
      gaussnoise: 0.3
      rgbshift: 0.3
      randomgamma: 0.3
      randombrightness: 0.5
      huesat: 0.5
    normalize:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]

MODEL:
  type: PoseResNet
  block: BasicBlock
  layers: [2, 2, 2, 2]
  dropout_prob: 0.0
  num_layers: 18
  include_top: False
  include_hm_decoder: True
  head_conv: 64
  use_c2: True
  use_c3: True
  use_c4: True
  use_c51: True
  efpn: True
  tfpn: False
  heads:
    hm: 1
    cls: 1
    cstency: 256
  INIT_WEIGHTS:
    num_layers: 18
    pretrained: True
    advprop: False

TRAIN:
  gpus: [0]
  batch_size: 16
  lr: 0.00005
  epochs: 3  # Try with 3 epochs first to test
  warm_up: 2
  every_val_epochs: 1
  loss:
    type: CombinedFocalLoss
    cls_lmda: 1
    hm_lmda: 10
    cstency_lmda: 100
    offset_lmda: 1 
    dst_hm_cls_lmda: 1  
    mse_reduction: sum
    use_target_weight: False
    ce_reduction: mean
  optimizer: Adam
  distributed: False
  resume: False
  tensorboard: False

TEST:
  gpus: [0]
  vis_hm: False
  threshold: 0.5
  flip_test: True
  video_level: False
